// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"
)

type User struct {
	ID           int64
	Username     string
	Email        string
	CreatedAt    time.Time
	PasswordHash string
}
